# Project identification
sonar.projectKey=zenkiet_ZenReply_666e9978-215f-4579-909a-a906d426d493
sonar.projectName=ZenReply
sonar.projectVersion=1.0

# Source code location
sonar.sources=.
sonar.exclusions=**/vendor/**,**/*.test.go,**/*.spec.ts,dist/**,node_modules/**,**/android/**,**/ios/**

# Language specific settings
sonar.go.goglobal.linter.enabled=true
sonar.javascript.linter.enabled=true
sonar.typescript.tsconfigPath=frontend/tsconfig.json
sonar.typescript.eslint.configPath=frontend/eslint.config.js

# Limit
sonar.javascript.node.maxspace=4096

# Encoding
sonar.sourceEncoding=UTF-8
