# Project identification
sonar.projectKey=zenkiet_ZenReply_666e9978-215f-4579-909a-a906d426d493
sonar.projectName=ZenReply
sonar.projectVersion=1.0

# Source code location
sonar.sources=.
sonar.exclusions=**/vendor/**,**/*.test.go,**/*.spec.ts,dist/**,node_modules/**,github/**

# Language specific settings
sonar.go.goglobal.linter.enabled=true
sonar.javascript.linter.enabled=true
sonar.typescript.tsconfigPath=tsconfig.json

# Encoding
sonar.sourceEncoding=UTF-8
